[project]
name = "text-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.9.0",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "ruff>=0.14.11",
]
